---
- name: Remove key file
  when: 
    - aptkey_name | length > 0
  block:
    - name: Remove file
      become: true
      ansible.builtin.file:
        path: "{{ aptkey_path }}/{{ aptkey_name }}"
        state: absent
